<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite id="0" name="/projects/challenge/src/tests/App.test.js" errors="0" package="/projects/challenge/src/tests/App.test.js" hostname="localhost" tests="9" failures="8" time="1.902" timestamp="2021-04-01T12:19:52">
    <properties>
    </properties>
    <testcase classname="Form Validation &lt;App /&gt;" name="renders without crashing" time="0">
    </testcase>
    <testcase classname="Form Validation &lt;App /&gt;" name="check default message" time="0">
      <failure message="Error: expect(received).toEqual(expected) // deep equality

Expected: &quot;Form is Incomplete!&quot;
Received: &quot;&quot;
    at Object.&lt;anonymous&gt; (/projects/challenge/src/tests/App.test.js:20:17)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:276:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:216:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:212:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:149:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:63:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:57:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:176:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:109:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:380:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:472:34)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="Form Validation &lt;App /&gt;" name="check if all forms fields exist" time="0">
      <failure message="Error: expect(received).toEqual(expected) // deep equality

Expected: 4
Received: 0
    at Object.&lt;anonymous&gt; (/projects/challenge/src/tests/App.test.js:26:17)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:276:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:216:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:212:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:149:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:63:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:57:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:176:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:109:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:380:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:472:34)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="Form Validation &lt;App /&gt;" name="check entire form validation when the form is valid" time="0">
      <failure message="Error: Method “simulate” is meant to be run on 1 node. 0 found instead.
    at ReactWrapper.single (/projects/challenge/node_modules/enzyme/src/ReactWrapper.js:1168:13)
    at ReactWrapper.simulate (/projects/challenge/node_modules/enzyme/src/ReactWrapper.js:665:17)
    at Object.&lt;anonymous&gt; (/projects/challenge/src/tests/App.test.js:32:24)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:276:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:216:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:212:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:149:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:63:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:57:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:176:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:109:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:380:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:472:34)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="Form Validation &lt;App /&gt;" name="check entire form validation when the name is invalid" time="0">
      <failure message="Error: Method “simulate” is meant to be run on 1 node. 0 found instead.
    at ReactWrapper.single (/projects/challenge/node_modules/enzyme/src/ReactWrapper.js:1168:13)
    at ReactWrapper.simulate (/projects/challenge/node_modules/enzyme/src/ReactWrapper.js:665:17)
    at Object.&lt;anonymous&gt; (/projects/challenge/src/tests/App.test.js:43:24)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:276:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:216:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:212:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:149:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:63:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:57:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:176:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:109:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:380:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:472:34)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="Form Validation &lt;App /&gt;" name="check entire form validation when the phone number is invalid" time="0">
      <failure message="Error: Method “simulate” is meant to be run on 1 node. 0 found instead.
    at ReactWrapper.single (/projects/challenge/node_modules/enzyme/src/ReactWrapper.js:1168:13)
    at ReactWrapper.simulate (/projects/challenge/node_modules/enzyme/src/ReactWrapper.js:665:17)
    at Object.&lt;anonymous&gt; (/projects/challenge/src/tests/App.test.js:54:24)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:276:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:216:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:212:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:149:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:63:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:57:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:176:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:109:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:380:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:472:34)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="Form Validation &lt;App /&gt;" name="check entire form validation when the email is invalid" time="0">
      <failure message="Error: Method “simulate” is meant to be run on 1 node. 0 found instead.
    at ReactWrapper.single (/projects/challenge/node_modules/enzyme/src/ReactWrapper.js:1168:13)
    at ReactWrapper.simulate (/projects/challenge/node_modules/enzyme/src/ReactWrapper.js:665:17)
    at Object.&lt;anonymous&gt; (/projects/challenge/src/tests/App.test.js:65:24)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:276:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:216:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:212:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:149:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:63:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:57:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:176:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:109:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:380:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:472:34)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="Form Validation &lt;App /&gt;" name="check entire form validation when the url is invalid" time="0">
      <failure message="Error: Method “simulate” is meant to be run on 1 node. 0 found instead.
    at ReactWrapper.single (/projects/challenge/node_modules/enzyme/src/ReactWrapper.js:1168:13)
    at ReactWrapper.simulate (/projects/challenge/node_modules/enzyme/src/ReactWrapper.js:665:17)
    at Object.&lt;anonymous&gt; (/projects/challenge/src/tests/App.test.js:76:24)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:276:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:216:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:212:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:149:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:63:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:57:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:176:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:109:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:380:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:472:34)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="Form Validation &lt;App /&gt;" name="check form validation when the entire form is invalid" time="0">
      <failure message="Error: Method “simulate” is meant to be run on 1 node. 0 found instead.
    at ReactWrapper.single (/projects/challenge/node_modules/enzyme/src/ReactWrapper.js:1168:13)
    at ReactWrapper.simulate (/projects/challenge/node_modules/enzyme/src/ReactWrapper.js:665:17)
    at Object.&lt;anonymous&gt; (/projects/challenge/src/tests/App.test.js:87:24)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:276:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:216:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:212:40)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:149:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:63:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:57:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:25:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:176:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:109:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:380:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:472:34)" type="AssertionError">
      </failure>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>